---
abstract: 'Data, client and server classes for XML-RPC'
author:
  - 'Randy J. Ray'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RPC-XML
no_index:
  directory:
    - t
    - inc
recommends:
  XML::LibXML: 1.70
requires:
  File::Spec: 0.8
  LWP: 5.834
  Scalar::Util: 1.19
  Test::More: 0
  XML::Parser: 2.31
  constant: 1.03
  perl: 5.006001
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=RPC-XML
  homepage: http://search.cpan.org/dist/RPC-XML
  repository: http://github.com/rjray/rpc-xml
version: 0.75
