---
abstract: 'Data, client and server classes for XML-RPC'
author:
  - 'Randy J. Ray'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RPC-XML
no_index:
  directory:
    - t
    - inc
recommends:
  Compress::Raw::Zlib: 2.063
  DateTime: 0.70
  DateTime::Format::ISO8601: 0.07
  XML::LibXML: 1.85
requires:
  File::Spec: 0.8
  LWP: 5.834
  Module::Load: 0.24
  Scalar::Util: 1.19
  Test::More: 0.94
  XML::Parser: 2.31
  constant: 1.03
  perl: 5.008008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=RPC-XML
  homepage: http://search.cpan.org/dist/RPC-XML
  repository: http://github.com/rjray/rpc-xml
version: 0.78
